# server port config
server:
  port: 8081
  
# oracle driver config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: campers
    password: campers
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
# /*  : 경로의 바로 하위에 있는 모든 경로 매핑. ex) AAA/* : AAA/BBB, AAA/CCC 해당, AAA/BBB/CCC 해당하지 않음  
# /** : 경로의 모든 하위 경로(디렉토리) 매핑  ex) AAA/** : AAA/BBB, AAA/CCC, AAA/BBB/CCC, AAA/BBB/CCC/.../.../... 전부 해당     

# logging level (root level - 전역설정)
logging:
  level:
    root: info
#logging level (package level - 지역설정)
custom:
  path:
    upload-images: 'D:/6__Framework/2_spring/boot_workspace/campers/src/main/resources/uploadFiles/'